// Package giui embeds Gi's built web front-end, which lives in rcarmo/fixtures-vibes (ui/gi) and reaches Gi through
// its references/fixtures-vibes submodule. Gi imports it as github.com/rcarmo/gi/references/fixtures-vibes/ui/gi.
package giui

import (
	"embed"
	"io/fs"
)

//go:embed all:internal/web/static
var static embed.FS

// Static is the served web root (index.html, css, fonts, js, dist, editor-vendor, icons).
var Static, _ = fs.Sub(static, "internal/web/static")

// ThemeCatalogue is the theme preset catalogue generated by build.js for the /theme command.
//
//go:embed internal/web/theme_catalogue.json
var ThemeCatalogue []byte
